
const $ = id => document.getElementById(id);
const money = n => '$' + Number(n || 0).toLocaleString('en-SG',{minimumFractionDigits:2,maximumFractionDigits:2});
const money0 = n => '$' + Number(n || 0).toLocaleString('en-SG',{maximumFractionDigits:0});
const uid = p => p + '-' + Math.random().toString(36).slice(2,8).toUpperCase();
const today = () => new Date().toISOString().slice(0,10);
const toast = msg => { const t=$('toast'); t.textContent=msg; t.style.display='block'; setTimeout(()=>t.style.display='none',2200); };
const NAV=[['dashboard','🏠','Dashboard'],['companies','🏢','Companies'],['clients','👥','Clients / Case'],['quotation','📄','Quotation'],['projects','🏗️','Project Costing'],['invoices','💳','Invoices & Payments'],['po','📦','PO / Supplier Aging'],['profit','📊','Profit & Commission'],['master','⚙️','Master Data'],['users','🔐','Users & Access']];
const PERMS=['view','create','edit','delete','approve','export'];
const MODULES=['Dashboard','Companies','Clients','Quotation','Project Costing','VO','PO','DO','Invoices','Profit','Master Data','Users'];
const seed={
 settings:{normalMarkup:30,maxMarkup:40,approvalAbove:40,paymentTriggerPct:30,rates:{carpenter:80,installer:60,technician:55},templates:['Modern ID Template','Minimal Residential Template','Commercial Project Template']},
 companies:[
  {id:'CO-001',name:'BRICK & DECOR PTE LTD',prefix:'BD',uen:'202400001A',gst:true,address:'1 Design Street Singapore 111111',email:'accounts@brickdecor.sg',bank:'DBS Current 123-456-789',active:true},
  {id:'CO-002',name:'BRICK & DECOR STUDIO PTE LTD',prefix:'BDS',uen:'202400002B',gst:true,address:'2 Studio Road Singapore 222222',email:'studio@brickdecor.sg',bank:'OCBC Current 222-333-444',active:true},
  {id:'CO-003',name:'BD COMMERCIAL PROJECTS PTE LTD',prefix:'BDC',uen:'202400003C',gst:true,address:'3 Commercial Avenue Singapore 333333',email:'commercial@brickdecor.sg',bank:'UOB Current 333-444-555',active:true},
  {id:'CO-004',name:'BD DESIGN & BUILD PTE LTD',prefix:'BDB',uen:'202400004D',gst:false,address:'4 Build Lane Singapore 444444',email:'build@brickdecor.sg',bank:'DBS Current 444-555-666',active:true},
  {id:'CO-005',name:'BD PROJECT SERVICES PTE LTD',prefix:'BDP',uen:'202400005E',gst:false,address:'5 Project Road Singapore 555555',email:'projects@brickdecor.sg',bank:'OCBC Current 555-666-777',active:true}
 ],
 users:[
  {id:'U-001',name:'Super Admin',email:'admin@brickdecor.sg',role:'Superadmin',companyIds:['ALL'],permissions:{},costVisibility:'All cost/profit/commission',audit:[]},
  {id:'U-002',name:'Aiden Lee',email:'aiden@brickdecor.sg',role:'ID / Salesperson',companyIds:['CO-001','CO-002'],permissions:{Quotation:['view','create','edit','export'],Clients:['view','create','edit'],VO:['view','create','edit'],DO:['view','create']},costVisibility:'Selling price and own commission only',audit:[]},
  {id:'U-003',name:'Rachel Lim',email:'rachel@brickdecor.sg',role:'Accounts',companyIds:['ALL'],permissions:{Invoices:['view','create','edit','export'],PO:['view','edit','approve','export'],Profit:['view','export']},costVisibility:'Invoice, supplier invoice, payment and report cost',audit:[]},
  {id:'U-004',name:'Alex Wong',email:'alex@brickdecor.sg',role:'Project Manager',companyIds:['CO-001','CO-003'],permissions:{'Project Costing':['view','create','edit','approve'],PO:['view','create','edit'],DO:['view','create','edit','approve']},costVisibility:'Project cost only',audit:[]}
 ],
 clients:[{id:'C-001',companyId:'CO-001',type:'Individual',name:'Jessica Tan',phone:'+65 9123 4567',email:'jessica.tan@email.com',address:'28A River Valley Road',lead:'Instagram Ad',notes:'Prefers light colour palette and soft-close fittings.'}],
 projects:[{id:'PRJ-001',companyId:'CO-001',name:'Condo Renovation - 28A',clientId:'C-001',client:'Jessica Tan',salesperson:'Aiden Lee',manager:'Alex Wong',type:'Condo Renovation',site:'28A River Valley Road #02-01',status:'In Progress',progress:55,start:'2025-05-12',target:'2025-06-30'}],
 items:[{id:'IT-001',desc:'Custom Kitchen Carpentry',cat:'Carpentry',unit:'Lot',cost:8000},{id:'IT-002',desc:'Quartz Kitchen Top',cat:'Surface',unit:'Lot',cost:3000},{id:'IT-003',desc:'Backsplash Porcelain',cat:'Tiles',unit:'Lot',cost:1600},{id:'IT-004',desc:'LED Strip Light Fitting',cat:'Electrical',unit:'Lot',cost:650}],
 quotes:[{id:'QT-001',companyId:'CO-001',projectId:'PRJ-001',client:'Jessica Tan',project:'Condo Renovation - 28A',salesperson:'Aiden Lee',template:'Modern ID Template',status:'Draft',versions:[{version:'v1',date:'2025-05-10',template:'Modern ID Template',total:17605,by:'Aiden Lee'}],items:[{itemId:'IT-001',desc:'Custom Kitchen Carpentry',cat:'Carpentry',qty:1,unit:'Lot',cost:8000,price:10400},{itemId:'IT-002',desc:'Quartz Kitchen Top',cat:'Surface',qty:1,unit:'Lot',cost:3000,price:4200},{itemId:'IT-003',desc:'Backsplash Porcelain',cat:'Tiles',qty:1,unit:'Lot',cost:1600,price:2160},{itemId:'IT-004',desc:'LED Strip Light Fitting',cat:'Electrical',qty:1,unit:'Lot',cost:650,price:845}]}],
 costs:[{id:'COST-1',projectId:'PRJ-001',cat:'Materials',desc:'Porcelain Tiles – Living Area',supplier:'Niro Granite Pte Ltd',invoiceNo:'INV-2025-0187',date:'2025-05-10',budget:2500,actual:2250,committed:0,status:'Approved by ID'},{id:'COST-2',projectId:'PRJ-001',cat:'Materials',desc:'Kitchen Cabinets – Package',supplier:'Carpentry Works',invoiceNo:'INV-2025-0192',date:'2025-05-12',budget:4800,actual:2400,committed:2400,status:'Pending ID Approval'},{id:'COST-3',projectId:'PRJ-001',cat:'Manpower',desc:'Carpentry Labour',supplier:'Internal Team',invoiceNo:'MP-2025-0007',date:'2025-05-08',budget:1600,actual:1120,committed:0,status:'Approved by ID'}],
 vos:[{id:'VO-001',companyId:'CO-001',projectId:'PRJ-001',project:'Condo Renovation - 28A',reason:'Additional storage requested by client',items:[{desc:'Kitchen Base Cabinet - Pull-out',type:'Added',qty:1,price:680},{desc:'Bathroom Faucet Upgrade',type:'Changed',qty:2,price:320}],status:'Pending'}],
 pos:[{id:'PO-001',companyId:'CO-001',projectId:'PRJ-001',supplier:'Supply Builders Pte Ltd',delivery:'2025-06-05',items:[{desc:'Porcelain Tile',cat:'Tiles',qty:120,price:28},{desc:'Kitchen Cabinet Package',cat:'Carpentry',qty:1,price:8500}],status:'Draft'}],
 dos:[{id:'DO-001',companyId:'CO-001',projectId:'PRJ-001',receiver:'Aiden Wong',signed:false,items:['Kitchen Cabinet','Kitchen Countertop','Wardrobe','Tiling','Painting'].map(x=>({desc:x,done:true})),status:'Draft'}],
 invoices:[{id:'INV-001',companyId:'CO-001',projectId:'PRJ-001',project:'Condo Renovation - 28A',client:'Jessica Tan',amount:18225,due:'2025-05-26',status:'Partially Paid',schedule:[{stage:'Deposit 30%',amount:5467.5,received:5467.5},{stage:'Hacking & Plumbing 30%',amount:5467.5,received:2757.5},{stage:'Carpentry & Tiling 20%',amount:3645,received:0},{stage:'Final Handover 20%',amount:3645,received:0}],payments:[{date:'2025-05-12',method:'Bank Transfer',amount:5467.5,ref:'RCPT-1001'},{date:'2025-05-24',method:'Bank Transfer',amount:2757.5,ref:'RCPT-1034'}]}],
 supplierInvoices:[{id:'SIN-001',supplier:'Niro Granite Pte Ltd',invoiceNo:'INV-2025-0187',projectId:'PRJ-001',companyId:'CO-001',amount:2250,paid:2250,date:'2025-05-10',due:'2025-06-10',approvedById:true},{id:'SIN-002',supplier:'Carpentry Works',invoiceNo:'INV-2025-0192',projectId:'PRJ-001',companyId:'CO-001',amount:4800,paid:2400,date:'2025-05-12',due:'2025-06-12',approvedById:false}]
};
let state = JSON.parse(localStorage.getItem('bd-v04-starter') || 'null') || seed;
let active='dashboard', projectSub='cost', filterText='';
function save(){localStorage.setItem('bd-v04-starter',JSON.stringify(state));}
function reset(){if(confirm('Reset all demo data?')){localStorage.removeItem('bd-v04-starter');state=JSON.parse(JSON.stringify(seed));show(active);toast('Demo reset');}}
function cls(s){return {'Paid':'greenp','Approved':'greenp','Approved by ID':'greenp','In Progress':'greenp','Planning':'bluep','Handover':'orangep','On Hold':'redp','Pending':'orangep','Pending ID Approval':'orangep','Partial':'orangep','Partially Paid':'orangep','Completed':'greenp','Draft':'bluep','Active':'greenp','Closed':'greenp','Sent':'greenp'}[s]||'bluep';}
function pill(s){return `<span class="pill ${cls(s)}">${s}</span>`;}
function co(id){return state.companies.find(c=>c.id===id) || state.companies[0];}
function companyOptions(val){return state.companies.map(c=>`<option value="${c.id}" ${c.id===val?'selected':''}>${c.name}</option>`).join('');}
function head(t,s,c,a=''){return `<div class="head"><div><div class="crumb">${c}</div><h1>${t}</h1><p class="sub">${s}</p></div><div class="actions">${a}</div></div>`;}
function field(id,label,value='',type='text',opts='',full=''){if(type==='textarea')return `<div class="field ${full}"><label>${label}</label><textarea id="${id}">${value||''}</textarea></div>`; if(type==='select')return `<div class="field ${full}"><label>${label}</label><select id="${id}">${opts}</select></div>`; return `<div class="field ${full}"><label>${label}</label><input id="${id}" type="${type}" value="${value??''}"></div>`;}
function opts(list,val){return list.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('');}
function quoteTotal(q){return q.items.reduce((a,b)=>a+(+b.price||0)*(+b.qty||0),0);}
function quoteCost(q){return q.items.reduce((a,b)=>a+(+b.cost||0)*(+b.qty||0),0);}
function invPaid(inv){return inv.payments.reduce((a,b)=>a+(+b.amount||0),0);}
function modal(html){$('modalBody').innerHTML=html;$('modal').classList.add('show');}
function closeModal(){$('modal').classList.remove('show');}
function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='brick-decor-v04-test-data.json';a.click();}
function printDoc(title,body,companyId){const c=co(companyId||state.companies[0].id);const w=window.open('','_blank');w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;margin:36px;color:#222}h1{color:#ff5b5f}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f7f7f7}.right{text-align:right}.muted{color:#666}</style></head><body><h1>${c.name}</h1><p class="muted">UEN: ${c.uen}<br>${c.address}<br>${c.email}<br>${c.bank}</p><h2>${title}</h2>${body}<script>window.print()<\/script></body></html>`);w.document.close();}
function layout(){ $('app').innerHTML = `<div class="app"><aside class="sidebar"><div class="brand"><div class="logo"></div><b>BRICK & DECOR</b></div><nav class="nav">${NAV.map(([id,ico,label])=>`<button class="${active===id?'active':''}" onclick="show('${id}')"><span>${ico}</span>${label}</button>`).join('')}</nav><div class="promo"><b>Starter Test v0.4</b><p>Dummy 5-company data, flexible permissions, quotation templates/version history, PO aging. Warranty and photo upload removed.</p></div></aside><main class="main"><div class="topbar"><input class="search" placeholder="Search anything..." oninput="filterText=this.value.toLowerCase();show(active)"><div class="user"><button class="btn small" onclick="exportJSON()">Export JSON</button><button class="btn small red" onclick="reset()">Reset</button><div class="avatar">A</div><div><b>Admin</b><div class="small">Superadmin</div></div></div></div><div class="content" id="content"></div></main></div>`;}
function show(id){active=id;layout();$('content').innerHTML=pages[id]();save();}
const pages={};
pages.dashboard=()=>{const sales=state.quotes.reduce((a,q)=>a+quoteTotal(q),0)+state.vos.reduce((a,v)=>a+v.items.reduce((x,i)=>x+i.qty*i.price,0),0);const actual=state.costs.reduce((a,c)=>a+(+c.actual||0),0);const paid=state.invoices.reduce((a,i)=>a+invPaid(i),0);const invTotal=state.invoices.reduce((a,i)=>a+i.amount,0);const supplierPending=state.supplierInvoices.reduce((a,s)=>a+(s.amount-s.paid),0);return head('Dashboard','Starter test overview using dummy company and project data.','Dashboard','<button class="btn primary" onclick="show(\'clients\')">+ New Case</button>')+`<div class="grid kpis">${[['Total Sales',sales,'💼'],['Pending Customer Payment',Math.max(invTotal-paid,0),'💰'],['Active Projects',state.projects.length,'🧰'],['Gross Profit',sales-actual,'📈'],['Supplier Unpaid',supplierPending,'📦'],['Commission Est.',Math.max((sales-actual)*.1,0),'💸']].map(x=>`<div class="card"><div>${x[2]}</div><div class="small">${x[0]}</div><div class="money">${typeof x[1]==='number'&&x[1]>50?money0(x[1]):x[1]}</div><div class="up">demo data</div></div>`).join('')}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Payment Collection</h3><div class="money">${money0(paid)}</div><div class="small">of ${money0(invTotal)}</div><br><div class="progress greenbar"><span style="width:${invTotal?paid/invTotal*100:0}%"></span></div></div><div class="card"><h3>Supplier Invoice Aging</h3>${supplierAgingTable(true)}</div></div><div class="card" style="margin-top:16px"><h3>Projects</h3>${projectTable()}</div>`;};
function projectTable(){const rows=state.projects.filter(p=>(p.name+p.client+p.salesperson+co(p.companyId).name).toLowerCase().includes(filterText||''));return `<table><thead><tr><th>Company</th><th>Project</th><th>Client</th><th>ID</th><th>Status</th><th>Progress</th><th>Action</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${co(p.companyId).prefix}</td><td><b>${p.name}</b><br><span class="small">${p.site}</span></td><td>${p.client}</td><td>${p.salesperson}</td><td>${pill(p.status)}</td><td><b>${p.progress}%</b><div class="progress"><span style="width:${p.progress}%"></span></div></td><td><button class="btn small" onclick="openProject('${p.id}')">Open</button></td></tr>`).join('')}</tbody></table>`;}
window.openProject=id=>{state.selectedProject=id;show('projects');};
pages.companies=()=>head('Company Master','Use dummy company data now; replace with real 4–5 company details later.','Companies','<button class="btn primary" onclick="addCompany()">+ Add Company</button>')+`<div class="card"><h3>Companies for project and document issuing</h3><table><thead><tr><th>Prefix</th><th>Company</th><th>UEN</th><th>GST</th><th>Email</th><th>Bank</th><th>Status</th></tr></thead><tbody>${state.companies.map(c=>`<tr><td><b>${c.prefix}</b></td><td>${c.name}<br><span class="small">${c.address}</span></td><td>${c.uen}</td><td>${c.gst?'Yes':'No'}</td><td>${c.email}</td><td>${c.bank}</td><td>${pill(c.active?'Active':'Inactive')}</td></tr>`).join('')}</tbody></table></div>`;
window.addCompany=()=>modal(`<h2>Add Company</h2><div class="form">${field('co_name','Company Name','New Company Pte Ltd')}${field('co_prefix','Document Prefix','NC')}${field('co_uen','UEN','202400000Z')}${field('co_gst','GST Registered','Yes','select',opts(['Yes','No'],'Yes'))}${field('co_addr','Address','Singapore')}${field('co_email','Email','accounts@company.sg')}${field('co_bank','Bank Details','DBS Current xxx')}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveCompany()">Save Company</button>`);
window.saveCompany=()=>{state.companies.push({id:uid('CO'),name:$('co_name').value,prefix:$('co_prefix').value,uen:$('co_uen').value,gst:$('co_gst').value==='Yes',address:$('co_addr').value,email:$('co_email').value,bank:$('co_bank').value,active:true});closeModal();toast('Company added');show('companies');};
pages.clients=()=>head('Clients / Case Opening','Create a case with company selection, client details, site address, lead source and assigned ID. No warranty/photo upload.','Clients > Case Opening','<button class="btn primary" onclick="newCase()">+ Create Case</button>')+`<div class="notice"><b>Company rule:</b> select the issuing company when opening project. Quotation, invoice, PO and DO follow this company by default.</div><div class="card"><h3>Case List</h3>${projectTable()}</div>`;
window.newCase=()=>modal(`<h2>Create New Case</h2><div class="form">${field('m_company','Issuing Company',state.companies[0].id,'select',companyOptions(state.companies[0].id))}${field('m_client','Client Name','New Client')}${field('m_phone','Phone','+65 ')}${field('m_email','Email','client@email.com')}${field('m_project','Project Name','New Renovation Project')}${field('m_type','Property / Project Type','Condo Renovation','select',opts(['Condo Renovation','HDB Renovation','Commercial Fit-out','Office Reinstatement'],'Condo Renovation'))}${field('m_site','Site Address','Singapore')}${field('m_sales','Assigned ID / Salesperson','Aiden Lee')}${field('m_manager','Project Manager','Alex Wong')}${field('m_lead','Lead Source','Instagram Ad','select',opts(['Instagram Ad','Referral','Website','Walk-in','Repeat Customer'],'Instagram Ad'))}${field('m_notes','Notes','Client requirement notes only. No warranty/photo required.','textarea','', 'full')}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveCase()">Create Case</button>`);
window.saveCase=()=>{const cid=uid('C');const pid=uid('PRJ');state.clients.push({id:cid,companyId:$('m_company').value,type:'Individual',name:$('m_client').value,phone:$('m_phone').value,email:$('m_email').value,address:$('m_site').value,lead:$('m_lead').value,notes:$('m_notes').value});state.projects.push({id:pid,companyId:$('m_company').value,name:$('m_project').value,clientId:cid,client:$('m_client').value,salesperson:$('m_sales').value,manager:$('m_manager').value,type:$('m_type').value,site:$('m_site').value,status:'Planning',progress:0,start:today(),target:today()});state.selectedProject=pid;closeModal();toast('Case created');show('clients');};
pages.quotation=()=>{let q=state.quotes[0];const valid=q.items.every(i=>i.price>=i.cost*(1+state.settings.normalMarkup/100)&&i.price<=i.cost*(1+state.settings.maxMarkup/100));return head('Quotation Builder','Markup validation, version history and 3 template selection.','Quotations > Builder','<button class="btn" onclick="addQuoteItem()">+ Add Item</button><button class="btn red" onclick="printQuote()">Generate Print</button><button class="btn primary" onclick="sendQuoteVersion()">Send / Save Version</button>')+`<div class="grid sidegrid"><div><div class="grid three"><div class="card"><h3>Company</h3><select onchange="qCompany(this.value)">${companyOptions(q.companyId)}</select></div><div class="card"><h3>Project</h3>${q.project}<br>ID: ${q.salesperson}</div><div class="card"><h3>Template</h3><select onchange="qTemplate(this.value)">${state.settings.templates.map(t=>`<option ${t===q.template?'selected':''}>${t}</option>`).join('')}</select></div></div><div class="notice"><b>Pricing Rule:</b> price must be between ${state.settings.normalMarkup}% and ${state.settings.maxMarkup}% markup. Change rule in Master Data.</div><div class="card"><h3>Quotation Items</h3><table><thead><tr><th>Item</th><th>Cost</th><th>Allowed Range</th><th>Qty</th><th>Your Price</th><th>Amount</th><th></th></tr></thead><tbody>${q.items.map((i,idx)=>{let min=i.cost*(1+state.settings.normalMarkup/100),max=i.cost*(1+state.settings.maxMarkup/100),ok=i.price>=min&&i.price<=max;return `<tr><td><b>${i.desc}</b><br><span class="small">${i.cat}</span></td><td>${money(i.cost)}</td><td>${money(min)} - ${money(max)}</td><td><input value="${i.qty}" type="number" min="1" style="width:64px" onchange="quoteEdit(${idx},'qty',this.value)"></td><td><input class="${ok?'ok':'bad'}" value="${i.price}" type="number" style="width:110px" onchange="quoteEdit(${idx},'price',this.value)"></td><td>${money(i.qty*i.price)}</td><td><span class="danger" onclick="deleteQuoteItem(${idx})">Delete</span></td></tr>`;}).join('')}</tbody></table></div><br><div class="card"><h3>Quotation Version History</h3><table><thead><tr><th>Version</th><th>Date</th><th>Template</th><th>Total</th><th>Sent By</th></tr></thead><tbody>${q.versions.map(v=>`<tr><td>${v.version}</td><td>${v.date}</td><td>${v.template}</td><td>${money(v.total)}</td><td>${v.by}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><h3>Pricing Summary</h3><div class="small">Approximate Cost</div><div class="money">${money(quoteCost(q))}</div><br><div class="small">Total Quotation</div><div class="total">${money(quoteTotal(q))}</div><br>${valid?pill('Approved').replace('Approved','All prices valid'):pill('On Hold').replace('On Hold','Price outside range')}<br><br><p><b>Document Company</b><br>${co(q.companyId).name}</p></div></div>`;};
window.qCompany=v=>{state.quotes[0].companyId=v;toast('Quotation company changed');save();show('quotation');};
window.qTemplate=v=>{state.quotes[0].template=v;toast('Template changed');save();show('quotation');};
window.quoteEdit=(idx,k,v)=>{let q=state.quotes[0];q.items[idx][k]=Number(v)||0;show('quotation');};
window.deleteQuoteItem=idx=>{state.quotes[0].items.splice(idx,1);toast('Item deleted');show('quotation');};
window.addQuoteItem=()=>modal(`<h2>Add Quotation Item</h2><div class="form">${field('qi_item','Item',state.items[0].desc,'select',opts(state.items.map(i=>i.desc),state.items[0].desc))}${field('qi_qty','Qty','1','number')}${field('qi_price','Your Price','0','number')}</div><p class="small">Leave price as 0 to auto use normal markup.</p><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveQuoteItem()">Add Item</button>`);
window.saveQuoteItem=()=>{let m=state.items.find(i=>i.desc==$('qi_item').value);let price=+$('qi_price').value||m.cost*(1+state.settings.normalMarkup/100);state.quotes[0].items.push({itemId:m.id,desc:m.desc,cat:m.cat,qty:+$('qi_qty').value||1,unit:m.unit,cost:m.cost,price});closeModal();toast('Quotation item added');show('quotation');};
window.sendQuoteVersion=()=>{let q=state.quotes[0];q.status='Sent';q.versions.push({version:'v'+(q.versions.length+1),date:today(),template:q.template,total:quoteTotal(q),by:q.salesperson});toast('Quotation version saved');show('quotation');};
window.printQuote=()=>{let q=state.quotes[0];printDoc('Quotation '+q.id,`<p>Client: ${q.client}<br>Project: ${q.project}<br>Template: ${q.template}</p><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Amount</th></tr>${q.items.map(i=>`<tr><td>${i.desc}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('')}<tr><th colspan="3" class="right">Total</th><th>${money(quoteTotal(q))}</th></tr></table>`,q.companyId);};
pages.projects=()=>{let p=state.projects.find(x=>x.id==(state.selectedProject||state.projects[0].id))||state.projects[0];let pcosts=state.costs.filter(c=>c.projectId==p.id);return head(p.name,'Project Costing with Real Cost, VO and DO under one page.','Project Costing','<button class="btn primary" onclick="addCost()">+ Add Cost Entry</button>')+`<div class="card"><b>Company:</b> ${co(p.companyId).name} &nbsp; <b>Client:</b> ${p.client} &nbsp; <b>Site:</b> ${p.site} &nbsp; ${pill(p.status)}<div class="tabs"><button class="${projectSub==='cost'?'active':''}" onclick="projectSub='cost';show('projects')">Real Cost</button><button class="${projectSub==='vo'?'active':''}" onclick="projectSub='vo';show('projects')">VO</button><button class="${projectSub==='do'?'active':''}" onclick="projectSub='do';show('projects')">DO / Handover</button><button class="${projectSub==='manpower'?'active':''}" onclick="projectSub='manpower';show('projects')">Manpower</button></div>${projectSub==='cost'?projectCostHtml(p,pcosts):projectSub==='vo'?projectVOHtml(p):projectSub==='do'?projectDOHtml(p):projectManpowerHtml(p)}</div>`;};
function projectCostHtml(p,pcosts){let budget=pcosts.reduce((a,c)=>a+c.budget,0),actual=pcosts.reduce((a,c)=>a+c.actual,0),committed=pcosts.reduce((a,c)=>a+c.committed,0);return `<div class="grid four"><div class="card"><div class="small">Budget</div><div class="money">${money(budget)}</div></div><div class="card"><div class="small">Actual</div><div class="money">${money(actual)}</div></div><div class="card"><div class="small">Committed</div><div class="money">${money(committed)}</div></div><div class="card"><div class="small">Projected</div><div class="money">${money(actual+committed)}</div></div></div><br><h3>Cost Entries</h3><table><thead><tr><th>Category</th><th>Description</th><th>Supplier</th><th>Invoice No.</th><th>Budget</th><th>Actual</th><th>ID Approval</th><th></th></tr></thead><tbody>${pcosts.map(c=>`<tr><td>${c.cat}</td><td>${c.desc}</td><td>${c.supplier}</td><td>${c.invoiceNo}</td><td>${money(c.budget)}</td><td>${money(c.actual)}</td><td>${pill(c.status)}</td><td><span class="click" onclick="approveCost('${c.id}')">Approve</span> | <span class="danger" onclick="delCost('${c.id}')">Delete</span></td></tr>`).join('')}</tbody></table>`;}
function projectVOHtml(p){let rows=state.vos.filter(v=>v.projectId===p.id);return `<h3>Variation Orders</h3><button class="btn primary" onclick="addVO()">+ Add VO</button><br><br><table><thead><tr><th>VO</th><th>Reason</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(v=>`<tr><td>${v.id}</td><td>${v.reason}</td><td>${money(v.items.reduce((a,i)=>a+i.qty*i.price,0))}</td><td>${pill(v.status)}</td><td><span class="click" onclick="approveVO('${v.id}')">Approve</span></td></tr>`).join('')}</tbody></table>`;}
function projectDOHtml(p){let d=state.dos.find(d=>d.projectId===p.id)||state.dos[0];return `<h3>Delivery Order / Handover</h3><div class="grid two"><div><table><thead><tr><th>Done</th><th>Item</th></tr></thead><tbody>${d.items.map((i,idx)=>`<tr><td><input type="checkbox" ${i.done?'checked':''} onchange="toggleDO(${idx},this.checked)"></td><td>${i.desc}</td></tr>`).join('')}</tbody></table></div><div>${field('do_receiver','Received By',d.receiver)}${field('do_sig','Signature Text',d.signed?'Signed by '+d.receiver:'')}<br>${pill(d.status)}<br><br><button class="btn red" onclick="printDO()">Generate DO</button> <button class="btn primary" onclick="recordDO()">Record Handover</button></div></div>`;}
function projectManpowerHtml(p){return `<h3>Manpower Rate Guide</h3><div class="grid three"><div class="card"><div class="small">Carpenter Rate</div><div class="money">${money(state.settings.rates.carpenter)}/hr</div></div><div class="card"><div class="small">Installer Rate</div><div class="money">${money(state.settings.rates.installer)}/hr</div></div><div class="card"><div class="small">Technician Rate</div><div class="money">${money(state.settings.rates.technician)}/hr</div></div></div><p class="small">For test, add manpower as a cost entry with category Manpower.</p>`;}
window.addCost=()=>{let p=state.projects.find(x=>x.id==(state.selectedProject||state.projects[0].id));modal(`<h2>Add Cost Entry</h2><div class="form">${field('co_cat','Category','Materials','select',opts(['Materials','Manpower','Transport','Misc'],'Materials'))}${field('co_desc','Description','New cost')}${field('co_supplier','Supplier / Paid To','Internal Team')}${field('co_budget','Budget','0','number')}${field('co_actual','Actual Cost','0','number')}${field('co_committed','Committed Cost','0','number')}${field('co_inv','Supplier Invoice No.','INV-TEST')}${field('co_status','ID Approval','Pending ID Approval','select',opts(['Pending ID Approval','Approved by ID'],'Pending ID Approval'))}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveCost('${p.id}')">Save Cost</button>`);};
window.saveCost=pid=>{state.costs.push({id:uid('COST'),projectId:pid,cat:$('co_cat').value,desc:$('co_desc').value,supplier:$('co_supplier').value,invoiceNo:$('co_inv').value,date:today(),budget:+$('co_budget').value||0,actual:+$('co_actual').value||0,committed:+$('co_committed').value||0,status:$('co_status').value});closeModal();toast('Cost added');show('projects');};
window.approveCost=id=>{state.costs.find(c=>c.id===id).status='Approved by ID';toast('Cost approved by ID');show('projects');};
window.delCost=id=>{state.costs=state.costs.filter(c=>c.id!==id);toast('Cost deleted');show('projects');};
window.addVO=()=>modal(`<h2>Add VO</h2><div class="form">${field('vo_reason','Reason','Client requested additional work')}${field('vo_item','Item','Additional cabinet')}${field('vo_qty','Qty','1','number')}${field('vo_price','Unit Price','500','number')}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveVO()">Save VO</button>`);
window.saveVO=()=>{let p=state.projects.find(x=>x.id==(state.selectedProject||state.projects[0].id));state.vos.push({id:uid('VO'),companyId:p.companyId,projectId:p.id,project:p.name,reason:$('vo_reason').value,items:[{desc:$('vo_item').value,type:'Added',qty:+$('vo_qty').value||1,price:+$('vo_price').value||0}],status:'Pending'});closeModal();toast('VO added');projectSub='vo';show('projects');};
window.approveVO=id=>{state.vos.find(x=>x.id===id).status='Approved';toast('VO approved');show(active);};
window.toggleDO=(i,val)=>{state.dos[0].items[i].done=val;save();};
window.recordDO=()=>{state.dos[0].receiver=$('do_receiver').value;state.dos[0].signed=true;state.dos[0].status='Completed';toast('Handover recorded');show('projects');};
window.printDO=()=>{let d=state.dos[0];printDoc('Delivery Order '+d.id,`<p>Receiver: ${d.receiver}<br>Status: ${d.status}</p><ul>${d.items.map(i=>`<li>${i.done?'✓':'□'} ${i.desc}</li>`).join('')}</ul>`,d.companyId);};
pages.invoices=()=>{let inv=state.invoices[0],paid=invPaid(inv),pending=inv.amount-paid,minDue=inv.amount*state.settings.paymentTriggerPct/100;return head('Invoices & Payments','Staged billing with received, unpaid, overdue and percentage trigger check.','Invoices & Payments','<button class="btn primary" onclick="recordPayment()">Record Payment</button><button class="btn red" onclick="printInvoice()">Generate Invoice</button>')+`<div class="grid four"><div class="card"><div class="small">Document Company</div><b>${co(inv.companyId).prefix}</b><br>${co(inv.companyId).name}</div><div class="card"><div class="small">Invoice Amount</div><div class="money">${money(inv.amount)}</div></div><div class="card"><div class="small">Received</div><div class="money">${money(paid)}</div></div><div class="card"><div class="small">Payment Trigger</div><div class="${paid<minDue?'down':'up'}">${paid<minDue?'Below required '+state.settings.paymentTriggerPct+'%':'Meets required '+state.settings.paymentTriggerPct+'%'}</div></div></div><br><div class="card"><h3>Payment Schedule</h3><table><thead><tr><th>Stage</th><th>Amount</th><th>Received</th><th>Status</th></tr></thead><tbody>${inv.schedule.map(s=>`<tr><td>${s.stage}</td><td>${money(s.amount)}</td><td>${money(s.received)}</td><td>${pill(s.received>=s.amount?'Paid':s.received>0?'Partially Paid':'Pending')}</td></tr>`).join('')}</tbody></table></div><br><div class="card"><h3>Payment History</h3><table><thead><tr><th>Date</th><th>Method</th><th>Amount</th><th>Ref</th></tr></thead><tbody>${inv.payments.map(p=>`<tr><td>${p.date}</td><td>${p.method}</td><td>${money(p.amount)}</td><td>${p.ref}</td></tr>`).join('')}</tbody></table></div>`;};
window.recordPayment=()=>modal(`<h2>Record Payment</h2><div class="form">${field('pay_date','Date',today(),'date')}${field('pay_method','Method','Bank Transfer','select',opts(['Bank Transfer','PayNow','Credit Card','Cash'],'Bank Transfer'))}${field('pay_amt','Amount','1000','number')}${field('pay_ref','Reference','RCPT-'+Math.floor(Math.random()*9999))}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="savePayment()">Save Payment</button>`);
window.savePayment=()=>{let inv=state.invoices[0];let amt=+$('pay_amt').value||0;inv.payments.push({date:$('pay_date').value,method:$('pay_method').value,amount:amt,ref:$('pay_ref').value});let remaining=amt;for(const s of inv.schedule){let need=s.amount-s.received;if(remaining>0&&need>0){let add=Math.min(remaining,need);s.received+=add;remaining-=add;}}if(invPaid(inv)>=inv.amount)inv.status='Paid';closeModal();toast('Payment recorded');show('invoices');};
window.printInvoice=()=>{let inv=state.invoices[0];printDoc('Invoice '+inv.id,`<p>Client: ${inv.client}<br>Project: ${inv.project}</p><p>Total: ${money(inv.amount)}<br>Paid: ${money(invPaid(inv))}<br>Pending: ${money(inv.amount-invPaid(inv))}</p>`,inv.companyId);};
pages.po=()=>head('PO / Supplier Aging','PO records, duplicate supplier invoice detection, paid/unpaid aging, ID approval and project cost allocation.','PO','<button class="btn primary" onclick="addSupplierInvoice()">+ Add Supplier Invoice</button><button class="btn red" onclick="printPO()">Generate PO</button>')+`<div class="grid two"><div class="card"><h3>Purchase Orders</h3><table><thead><tr><th>Company</th><th>PO</th><th>Supplier</th><th>Delivery</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${state.pos.map(po=>`<tr><td>${co(po.companyId).prefix}</td><td>${po.id}</td><td>${po.supplier}</td><td>${po.delivery}</td><td>${money(po.items.reduce((a,i)=>a+i.qty*i.price,0))}</td><td>${pill(po.status)}</td><td><span class="click" onclick="approvePO('${po.id}')">Approve</span></td></tr>`).join('')}</tbody></table></div><div class="card"><h3>Supplier Invoice Aging</h3>${supplierAgingTable(false)}</div></div>`;
function supplierAgingTable(compact){return `<table><thead><tr><th>Supplier</th><th>Invoice No.</th><th>Amount</th><th>Unpaid</th>${compact?'':'<th>Project</th><th>ID Approval</th><th>Duplicate</th>'}</tr></thead><tbody>${state.supplierInvoices.map(s=>{let dup=state.supplierInvoices.filter(x=>x.supplier===s.supplier&&x.invoiceNo===s.invoiceNo).length>1;let p=state.projects.find(p=>p.id===s.projectId);return `<tr><td>${s.supplier}</td><td>${s.invoiceNo}</td><td>${money(s.amount)}</td><td class="${s.amount-s.paid>0?'warn':'up'}">${money(s.amount-s.paid)}</td>${compact?'':`<td>${p?p.name:'-'}</td><td>${s.approvedById?pill('Approved by ID'):pill('Pending ID Approval')}</td><td>${dup?'<span class="down">Duplicate</span>':'-'}</td>`}</tr>`;}).join('')}</tbody></table>`;}
window.addSupplierInvoice=()=>modal(`<h2>Add Supplier Invoice</h2><div class="form">${field('si_supplier','Supplier','Niro Granite Pte Ltd')}${field('si_inv','Invoice No.','INV-2025-0187')}${field('si_amount','Amount','1000','number')}${field('si_paid','Paid Amount','0','number')}${field('si_project','Allocate to Project',state.projects[0].id,'select',state.projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''))}${field('si_approved','ID Approved?','No','select',opts(['No','Yes'],'No'))}</div><p class="small">Use same supplier + invoice no. to test duplicate warning.</p><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveSupplierInvoice()">Save Invoice</button>`);
window.saveSupplierInvoice=()=>{let p=state.projects.find(p=>p.id===$('si_project').value);state.supplierInvoices.push({id:uid('SIN'),supplier:$('si_supplier').value,invoiceNo:$('si_inv').value,projectId:p.id,companyId:p.companyId,amount:+$('si_amount').value||0,paid:+$('si_paid').value||0,date:today(),due:today(),approvedById:$('si_approved').value==='Yes'});closeModal();toast('Supplier invoice added');show('po');};
window.approvePO=id=>{state.pos.find(x=>x.id===id).status='Approved';toast('PO approved');show('po');};
window.printPO=()=>{let po=state.pos[0];printDoc('Purchase Order '+po.id,`<p>Supplier: ${po.supplier}<br>Delivery: ${po.delivery}</p><table>${po.items.map(i=>`<tr><td>${i.desc}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('')}</table>`,po.companyId);};
pages.profit=()=>{const sales=state.quotes.reduce((a,q)=>a+quoteTotal(q),0)+state.vos.reduce((a,v)=>a+v.items.reduce((x,i)=>x+i.qty*i.price,0),0);const actual=state.costs.reduce((a,c)=>a+c.actual,0);const gross=sales-actual;const commission=Math.max(gross*.1,0);return head('Profit & Commission','Final earning report without warranty impact.','Reports','<button class="btn primary" onclick="exportJSON()">Export Report Data</button>')+`<div class="grid kpis">${[['Total Sales',sales],['Actual Cost',actual],['Gross Profit',gross],['Company Profit',gross-commission],['Commission Est.',commission],['Profit Margin',sales?(gross/sales*100).toFixed(1)+'%':'0%']].map(x=>`<div class="card"><div class="small">${x[0]}</div><div class="money">${typeof x[1]==='number'?money0(x[1]):x[1]}</div></div>`).join('')}</div><br><div class="card"><h3>Project Profit Comparison</h3><table><thead><tr><th>Company</th><th>Project</th><th>Salesperson</th><th>Sales</th><th>Actual Cost</th><th>Profit</th><th>Commission Est.</th></tr></thead><tbody>${state.projects.map(p=>{let qs=state.quotes.filter(q=>q.projectId==p.id).reduce((a,q)=>a+quoteTotal(q),0);let vo=state.vos.filter(v=>v.projectId==p.id).reduce((a,v)=>a+v.items.reduce((x,i)=>x+i.qty*i.price,0),0);let c=state.costs.filter(c=>c.projectId==p.id).reduce((a,c)=>a+c.actual,0);let profit=qs+vo-c;return `<tr><td>${co(p.companyId).prefix}</td><td>${p.name}</td><td>${p.salesperson}</td><td>${money(qs+vo)}</td><td>${money(c)}</td><td class="${profit>=0?'up':'down'}">${money(profit)}</td><td>${money(Math.max(profit*.1,0))}</td></tr>`;}).join('')}</tbody></table></div>`;};
pages.master=()=>head('Master Data','Edit pricing rules, quotation templates, payment trigger and manpower rates.','Master Data','<button class="btn primary" onclick="saveSettings()">Save Settings</button><button class="btn" onclick="addMasterItem()">+ Add Item</button>')+`<div class="grid three"><div class="card"><h3>Pricing Rules</h3>${field('set_normal','Normal Markup %',state.settings.normalMarkup,'number')}${field('set_max','Max ID Markup %',state.settings.maxMarkup,'number')}${field('set_above','Approval Above %',state.settings.approvalAbove,'number')}${field('set_paypct','Payment Trigger %',state.settings.paymentTriggerPct,'number')}</div><div class="card"><h3>Quotation Templates</h3>${state.settings.templates.map((t,i)=>field('tpl'+i,'Template '+(i+1),t)).join('')}</div><div class="card"><h3>Manpower Rates</h3>${field('rate_carpenter','Carpenter / Hour',state.settings.rates.carpenter,'number')}${field('rate_installer','Installer / Hour',state.settings.rates.installer,'number')}${field('rate_technician','Technician / Hour',state.settings.rates.technician,'number')}</div></div><br><div class="card"><h3>Item Master</h3><table><thead><tr><th>Item</th><th>Category</th><th>Unit</th><th>Cost</th><th>Min Selling</th><th>Max Selling</th><th></th></tr></thead><tbody>${state.items.map(i=>`<tr><td>${i.desc}</td><td>${i.cat}</td><td>${i.unit}</td><td>${money(i.cost)}</td><td>${money(i.cost*(1+state.settings.normalMarkup/100))}</td><td>${money(i.cost*(1+state.settings.maxMarkup/100))}</td><td><span class="danger" onclick="delMasterItem('${i.id}')">Delete</span></td></tr>`).join('')}</tbody></table></div>`;
window.saveSettings=()=>{state.settings.normalMarkup=+$('set_normal').value||30;state.settings.maxMarkup=+$('set_max').value||40;state.settings.approvalAbove=+$('set_above').value||40;state.settings.paymentTriggerPct=+$('set_paypct').value||30;state.settings.templates=state.settings.templates.map((_,i)=>$('tpl'+i).value);state.settings.rates={carpenter:+$('rate_carpenter').value||0,installer:+$('rate_installer').value||0,technician:+$('rate_technician').value||0};toast('Settings saved');show('master');};
window.addMasterItem=()=>modal(`<h2>Add Master Item</h2><div class="form">${field('mi_desc','Item Description','New Item')}${field('mi_cat','Category','Carpentry','select',opts(['Carpentry','Tiles','Electrical','Surface','Labour'],'Carpentry'))}${field('mi_unit','Unit','Lot')}${field('mi_cost','Approx Cost','1000','number')}</div><br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveMasterItem()">Save Item</button>`);
window.saveMasterItem=()=>{state.items.push({id:uid('IT'),desc:$('mi_desc').value,cat:$('mi_cat').value,unit:$('mi_unit').value,cost:+$('mi_cost').value||0});closeModal();toast('Master item added');show('master');};
window.delMasterItem=id=>{state.items=state.items.filter(i=>i.id!==id);toast('Master item deleted');show('master');};
pages.users=()=>head('Users & Flexible Access','Superadmin can edit staff role, company access, permission matrix and cost visibility.','Users & Access','<button class="btn primary" onclick="addUser()">+ Add User</button>')+`<div class="card"><h3>Staff List</h3><table><thead><tr><th>Name</th><th>Role</th><th>Company Access</th><th>Cost Visibility</th><th>Action</th></tr></thead><tbody>${state.users.map(u=>`<tr><td><b>${u.name}</b><br><span class="small">${u.email}</span></td><td>${u.role}</td><td>${u.companyIds.includes('ALL')?'<span class="company-chip">All Companies</span>':u.companyIds.map(id=>`<span class="company-chip">${co(id).prefix}</span>`).join('')}</td><td>${u.costVisibility}</td><td><button class="btn small" onclick="editUser('${u.id}')">Edit Access</button></td></tr>`).join('')}</tbody></table></div><br><div class="card"><h3>Permission Matrix Preview</h3><div class="matrix"><div class="h wide">Module</div>${PERMS.map(p=>`<div class="h">${p}</div>`).join('')}${MODULES.map(m=>`<div class="wide"><b>${m}</b></div>${PERMS.map(p=>`<div>☐</div>`).join('')}`).join('')}</div></div><br><div class="card"><h3>Access Audit Log</h3><table><thead><tr><th>Date</th><th>User</th><th>Action</th></tr></thead><tbody>${state.users.flatMap(u=>(u.audit||[]).map(a=>`<tr><td>${a.date}</td><td>${u.name}</td><td>${a.action}</td></tr>`)).join('') || '<tr><td colspan="3">No audit record yet. Edit a user to create one.</td></tr>'}</tbody></table></div>`;
window.addUser=()=>{state.users.push({id:uid('U'),name:'New User',email:'new@brickdecor.sg',role:'Viewer',companyIds:['CO-001'],permissions:{},costVisibility:'No cost visibility',audit:[{date:new Date().toLocaleString(),action:'User created'}]});toast('User added');show('users');};
window.editUser=id=>{let u=state.users.find(x=>x.id===id);let companyChecks=state.companies.map(c=>`<label><input type="checkbox" class="cmp" value="${c.id}" ${u.companyIds.includes('ALL')||u.companyIds.includes(c.id)?'checked':''}> ${c.name}</label><br>`).join('');let matrix=`<div class="matrix"><div class="h wide">Module</div>${PERMS.map(p=>`<div class="h">${p}</div>`).join('')}${MODULES.map(m=>`<div class="wide"><b>${m}</b></div>${PERMS.map(p=>`<div><input type="checkbox" class="perm" data-m="${m}" value="${p}" ${(u.permissions[m]||[]).includes(p)||u.role==='Superadmin'?'checked':''}></div>`).join('')}`).join('')}</div>`;modal(`<h2>Edit Access - ${u.name}</h2><div class="form">${field('u_name','Name',u.name)}${field('u_email','Email',u.email)}${field('u_role','Main Role',u.role,'select',opts(['Superadmin','Admin','ID / Salesperson','Project Manager','Accounts','Viewer'],u.role))}${field('u_cost','Cost Visibility',u.costVisibility,'select',opts(['All cost/profit/commission','Project cost only','Invoice/supplier cost only','Selling price and own commission only','No cost visibility'],u.costVisibility))}</div><br><h3>Company Access</h3><label><input id="u_all" type="checkbox" ${u.companyIds.includes('ALL')?'checked':''}> All companies</label><br>${companyChecks}<br><h3>Module Permission Matrix</h3>${matrix}<br><button class="btn" onclick="closeModal()">Cancel</button> <button class="btn primary" onclick="saveUserAccess('${id}')">Save Access</button>`);};
window.saveUserAccess=id=>{let u=state.users.find(x=>x.id===id);u.name=$('u_name').value;u.email=$('u_email').value;u.role=$('u_role').value;u.costVisibility=$('u_cost').value;u.companyIds=$('u_all').checked?['ALL']:[...document.querySelectorAll('.cmp:checked')].map(x=>x.value);let perms={};document.querySelectorAll('.perm:checked').forEach(x=>{perms[x.dataset.m]=perms[x.dataset.m]||[];perms[x.dataset.m].push(x.value);});u.permissions=perms;u.audit=u.audit||[];u.audit.push({date:new Date().toLocaleString(),action:'Access updated by Superadmin'});closeModal();toast('User access updated');show('users');};
$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
show('dashboard');
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
